//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDb_Evidence
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentImage
    {
        public int StudentId { get; set; }
        public byte[] Picture { get; set; }
    }
}
